export const PASS_DATA_TO_CARD = "PASS_DATA_TO_CARD";
export const DELETE_USER = "DELETE_USER";
export const TOGGLE_STATUS = "TOGGLE_STATUS";
export const MOUSE_LEAVE = "MOUSE_LEAVE";
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
