export const userData = [
  {
    id: 1,
    name: "Jana Strassmann",
    email: "batz.mortimer@yahoo.com",
    status: "Active",
    plan: "standard",
    access: "Owner",
    avatar: require("../images/Jana-Strassmann.jpeg"),
  },
  {
    id: 2,
    name: "Jube Bowman",
    email: "ulirich.owen@kristin.biz",
    status: "Inactive",
    plan: "standard",
    access: "Manager",
    avatar: require("../images/Jube-Bowman.jpg"),
  },
  {
    id: 3,
    name: "Kwak Seang-Min",
    email: "kale_lehner@yahoo.com",
    status: "Inactive",
    plan: "Non-standard",
    access: "Read",
    avatar: require("../images/kwak-Seong-Min.jpg"),
  },
  {
    id: 4,
    name: "Leon Hunt",
    email: "ullrich.owen@kristin.biz",
    status: "Inactive",
    plan: "standard",
    access: "Manager",
    avatar: require("../images/Nitithorn-Prinya.jpg"),
  },
  {
    id: 5,
    name: "Nitithon Prinya",
    email: "ullrich.owen@kristin.biz",
    status: "Inactive",
    plan: "standard",
    access: "Manager",
    avatar: require("../images/Nombeko-Mabandia.jpg"),
  },
  {
    id: 6,
    name: "Nombeko Mabandia",
    email: "kale_lehner@yahoo.com",
    status: "Inactive",
    plan: "standard",
    access: "Read",
    avatar: require("../images/Siri-Jakobsson.jpg"),
  },
  {
    id: 7,
    name: "Nwoye Akachi",
    email: "ullrich.owen@kristin.biz",
    status: "Inactive",
    plan: "standard",
    access: "Manager",
    avatar: require("../images/Jana-Strassmann.jpeg"),
  },
  {
    id: 8,
    name: "Paulina Gayoso",
    email: "kale_lehner@yahoo.com",
    status: "Inactive",
    plan: "standard",
    access: "Read",
    avatar: require("../images/Jube-Bowman.jpg"),
  },
  {
    id: 9,
    name: "Phawta Tuntayakul",
    email: "ullrich.owen@kristin.biz",
    status: "Inactive",
    plan: "standard",
    access: "Manager",
    avatar: require("../images/Nitithorn-Prinya.jpg"),
  },
  {
    id: 10,
    name: "Siri Jakobsson",
    email: "ullrich.owen@kristin.biz",
    status: "Inactive",
    plan: "standard",
    access: "Manager",
    avatar: require("../images/Siri-Jakobsson.jpg"),
  },
];
