export const userData = [
  {
    id: 1,
    name: "Jana Strassmann",
    email: "batz.mortimer@yahoo.com",
    status: "Active",
    plan: "Standard",
    access: "Owner",
    avatar: require("../images/Jana-Strassmann.jpeg"),
    progressValue: 20,
    reviewed: 2450,
    clicks: 5000,
  },
  {
    id: 2,
    name: "Jube Bowman",
    email: "ulirich.owen@kristin.biz",
    status: "Inactive",
    plan: "Standard",
    access: "Manager",
    avatar: require("../images/Jube-Bowman.jpg"),
    progressValue: 32,
    reviewed: 4460,
    clicks: 3000,
  },
  {
    id: 3,
    name: "Kwak Seang-Min",
    email: "kale_lehner@yahoo.com",
    status: "Inactive",
    plan: "Non-standard",
    access: "Read",
    avatar: require("../images/kwak-Seong-Min.jpg"),
    progressValue: 40,
    reviewed: 1476,
    clicks: 4000,
  },
  {
    id: 4,
    name: "Leon Hunt",
    email: "ullrich.owen@kristin.biz",
    status: "Inactive",
    plan: "Standard",
    access: "Manager",
    avatar: require("../images/Nitithorn-Prinya.jpg"),
    progressValue: 22,
    reviewed: 2450,
    clicks: 5000,
  },
  {
    id: 5,
    name: "Nitithon Prinya",
    email: "ullrich.owen@kristin.biz",
    status: "Inactive",
    plan: "Standard",
    access: "Manager",
    avatar: require("../images/Nombeko-Mabandia.jpg"),
    progressValue: 50,
    reviewed: 2456,
    clicks: 5000,
  },
  {
    id: 6,
    name: "Nombeko Mabandia",
    email: "kale_lehner@yahoo.com",
    status: "Inactive",
    plan: "Standard",
    access: "Read",
    avatar: require("../images/Siri-Jakobsson.jpg"),
    progressValue: 55,
    reviewed: 24450,
    clicks: 5000,
  },
  {
    id: 7,
    name: "Nwoye Akachi",
    email: "ullrich.owen@kristin.biz",
    status: "Inactive",
    plan: "Standard",
    access: "Manager",
    avatar: require("../images/Jana-Strassmann.jpeg"),
    progressValue: 20,
    reviewed: 6450,
    clicks: 1200,
  },
  {
    id: 8,
    name: "Paulina Gayoso",
    email: "kale_lehner@yahoo.com",
    status: "Inactive",
    plan: "Standard",
    access: "Read",
    avatar: require("../images/Jube-Bowman.jpg"),
    progressValue: 42,
    reviewed: 1450,
    clicks: 2500,
  },
  {
    id: 9,
    name: "Phawta Tuntayakul",
    email: "ullrich.owen@kristin.biz",
    status: "Inactive",
    plan: "Standard",
    access: "Manager",
    avatar: require("../images/Nitithorn-Prinya.jpg"),
    progressValue: 70,
    reviewed: 350,
    clicks: 3500,
  },
  {
    id: 10,
    name: "Siri Jakobsson",
    email: "ullrich.owen@kristin.biz",
    status: "Inactive",
    plan: "Standard",
    access: "Manager",
    avatar: require("../images/Siri-Jakobsson.jpg"),
    progressValue: 65,
    reviewed: 3550,
    clicks: 5600,
  },
];
